wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://nexus.corp.redhat.com/repository/information-retrieval-maven2//org/apache/maven/apache-maven/3.9.6/apache-maven-3.9.6-bin.zip
